Repository leapfrogtechnology/chill, pull requests merged in 2019-03, with the labels that each got.

#60 Update Chill License
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  core/LICENSE
  dashboard/LICENSE.md
  monitor/LICENSE
Labels: documentation

#61 Add release and changelog generation script
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  scripts/release.sh
Labels: documentation, script

#62 Update README to add the new chill logo and the badges
  README.md
  chill.png
Labels: documentation

#63 Update chill logo
  README.md
  chill.png
Labels: design, documentation

#64 Create https util to get SSL info for given host
  monitor/src/utils/https.js
Labels: monitor, util

#70 Add prettier and eslint-config-leapfrog
  .prettierrc
  api/.eslintrc
  api/.eslintrc.yml
  api/package.json
  api/src/controllers/home.js
  api/src/controllers/service.js
  api/src/controllers/status.js
  api/src/controllers/statusLog.js
  api/src/docs/status.js
  api/src/index.js
  api/src/init.js
  api/src/middlewares/errorHandler.js
  api/src/models/Service.js
  api/src/models/Status.js
  api/src/models/StatusLog.js
  api/src/queries/status.js
  api/src/schema/statusLog.js
  api/src/scripts/synchronize.js
  api/src/services/persistence.js
  api/src/services/service.js
  api/src/services/status.js
  api/src/services/statusLog.js
  api/src/utils/buildError.js
  api/src/utils/db.js
  api/src/utils/logger.js
  api/src/utils/string.js
  api/src/utils/swagger.js
  api/src/utils/validator.js
  api/src/validators/statusLog.js
  api/yarn.lock
Labels: improvement
